export const DB_CONNECTION = 'DB_CONNECTION';
export const PROJECT_REPOSITORY = 'PROJECT_REPOSITORY';
export const GAME_OBJECT_REPOSITORY = 'GAME_OBJECT_REPOSITORY';
export const PAGE_REPOSITORY = 'PAGE_REPOSITORY';
export const BLOCK_REPOSITORY = 'BLOCK_REPOSITORY';
export const UNIT_OF_WORK = 'UNIT_OF_WORK';
